### ISSUE TITLE
Counter no longer works

### ISSUE THREAD

**Issue by 2dnerd** [Stvad/Asana-counter#3]
asana’s css changed because of which the script no longer works on my tasks or on any other project page

![image](https://user-images.githubusercontent.com/1686985/28903026-3987fd88-7820-11e7-8c68-c6e478969ed8.png)

![image](https://user-images.githubusercontent.com/1686985/28903030-4286f704-7820-11e7-9f94-fa32d53eeea3.png)

**Comment by Stvad** [comment]
Still, works on 'My tasks' page for me. Going to investigate the project page problems today.

**Comment by Stvad** [comment]
I've updated the script. It's operational again now for both views.
